version: '3'

services:
  app:
    build: .
    ports:
      - "7000:7000"
    command: yarn start
    depends_on:
        - db
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_backend
    environment:
      MYSQL_ROOT_PASSWORD: heaven
      MYSQL_DATABASE: database
    volumes:
      - ./dump:/docker-entrypoint-initdb.d


